/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 ipad.gltf --transform 
Files: ipad.gltf [3.81MB] > C:\Users\sim\Downloads\apple_ipad_pro\ipad-transformed.glb [223.23KB] (94%)
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/apple-ipad-pro-e5ffb3c80b2d4d6690249f8ee2bdafbe
Title: Apple iPad Pro
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ipad-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.iPad_Pro_2020_Body_0.geometry} material={materials.PaletteMaterial001} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.iPad_Pro_2020_screen_0.geometry} material={materials.screen} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.camera_module_glass_0.geometry} material={materials.PaletteMaterial002} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes['camera1_camera1(2)_0'].geometry} material={materials.camera12} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.camera_module2001_Camera_Flash_0.geometry} material={materials.Camera_Flash} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.camera_module2001_Mic_0.geometry} material={materials.material} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/ipad-transformed.glb')
